config/routes.rb
Rails.application.routes.draw do

  scope module: 'public' do

    # homes
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    #customers
    resources :customers, only: [:edit]
    get 'customers/my_page' => 'customers#show'
    patch 'customers/infomation' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw'  => 'customers#withdraw'

    #large_categories
    get 'categories' => 'large_categories#index'

    #quizzes
    get 'quizzes' => 'quizzes#index'
    get 'quizzes/shuffle' => 'quizzes#shuffle'

    #mock_exams
    resources :mock_exams, only: [:index, :create, :show, :destroy]

    #answers
    resources :answers, only: [:create]

    #board_posts
    resources :board_posts, only: [:index, :new, :show, :create, :destroy]
    get 'board_post/my_posts' => 'board_posts#my_posts'

    #comments
    resources :comments, only: [:create, :destroy]
    get 'comment/my_comments' => 'comments#my_comments'

    #items
    resources :items, only: [:index, :show]


  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do

    #large_categories
    resources :large_categories, only: [:index]
    post 'large_create' => 'large_categories#large_create'
    delete 'large_destroy/:id' => 'large_categories#large_destroy', as: 'large_destroy'
    post 'medium_create' => 'large_categories#medium_create'
    delete 'medium_destroy/:id' => 'large_categories#medium_destroy', as: 'medium_destroy'
    post 'small_create' => 'large_categories#small_create'
    delete 'small_destroy/:id' => 'large_categories#small_destroy', as: 'small_destroy'

    #items
    resources :items, only: [:new, :create, :edit, :update, :destroy]

    #quizzes
    resources :quizzes, only: [:create, :edit, :update, :destroy]

    #customers
    resources :customers, only: [:index, :edit, :update]

    #bord_posts
    resources :board_posts, only: [:destroy]

    #comments
    resources :comments, only: [:destroy]

  end

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :quizzes, dependent: :destroy
  has_one_attached :image
  has_many_attached :other_images
  has_one_attached :number_a_image
  has_one_attached :number_b_image
  has_one_attached :number_c_image

  belongs_to :large_category
  belongs_to :medium_category
  belongs_to :small_category

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  	end
  	image.variant(resize_to_limit: [width, height]).processed
  end

  def get_other_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  	end
  	other_image.variant(resize_to_limit: [width, height]).processed
  end

  def get_number_a_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  	end
  	number_a_image.variant(resize_to_limit: [width, height]).processed
  end

  def get_number_b_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  	end
  	number_b_image.variant(resize_to_limit: [width, height]).processed
  end

  def get_number_c_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  	end
  	number_c_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new

    if admin_signed_in?

      @items = Item.all
      @item = Item.new
      @large_categories = LargeCategory.all
      @@small_category = 0
      @@edit_small_category = 0

      if params[:large_category_id].present?
        @@large_category = LargeCategory.find(params[:large_category_id])
        @medium_categories = @@large_category.medium_categories
        @large_category = @@large_category
      end

      if params[:medium_category_id].present?
        @@medium_category = MediumCategory.find(params[:medium_category_id])
        @medium_category = @@medium_category
        @small_categories = @@medium_category.small_categories
      end

      if params[:small_category_id].present?
        @@small_category = SmallCategory.find(params[:small_category_id])
        @small_category = @@small_category
      end

    else
      redirect_to root_path
    end

  end

  def create
    @item = Item.new(item_params)

    if @@small_category == 0
    else
      @item.large_category_id = @@small_category.medium_category.large_category.id
      @item.medium_category_id = @@small_category.medium_category.id
      @item.small_category_id = @@small_category.id
    end

    if @item.save
      redirect_to item_path(@item.id)
    else
      @large_categories = LargeCategory.all
      render action: :new
    end
  end

  def edit
    if admin_signed_in?
      @large_categories = LargeCategory.all

      @@edit_large_category = 0
      @@edit_medium_category = 0
      @@edit_small_category = 0

      if params[:large_category_id].present?
        @@edit_large_category = LargeCategory.find(params[:large_category_id])
        @medium_categories = @@edit_large_category.medium_categories
        @large_category = @@edit_large_category
      end

      if params[:medium_category_id].present?
        @@edit_medium_category = MediumCategory.find(params[:medium_category_id])
        @medium_category = @@edit_medium_category
        @small_categories = @@edit_medium_category.small_categories
      end

      if params[:small_category_id].present?
        @@edit_small_category = SmallCategory.find(params[:small_category_id])
        @small_category = @@edit_small_category
      end
      @item = Item.find(params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    if admin_signed_in?

      @item = Item.find(params[:id])
      if @@edit_small_category == 0
      else
        @item.large_category_id = @@edit_small_category.medium_category.large_category.id
        @item.medium_category_id = @@edit_small_category.medium_category.id
        @item.small_category_id = @@edit_small_category.id
      end
      if @item.update(item_params)
        redirect_to item_path(@item.id)
      else
        @large_categories = LargeCategory.all
        render :edit
      end

      if params[:item][:other_image_ids]
        params[:item][:other_image_ids].each do |other_image_id|
          image = @item.other_images.find(other_image_id)
          image.purge
        end
      end

    else
      redirect_to root_path
    end
  end

  def destroy
    if admin_signed_in?
      @item = Item.find(params[:id])
      @item.destroy
      redirect_to items_path(small_category_id: @item.small_category.id)
    else
      redirect_to root_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :information, :commentary, :reading, :image, :large_category_id, :medium_category_id, :small_category_id, other_images: [])
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<p>
  <% if @item.errors.any? %>
    <% @item.errors.full_messages.each do |messeage| %>
      <div>・<%= messeage %></div>
    <% end %>
  <% end %>
</p>

<div class="flex">

  <div class="title">項目編集</div>
  <div><%= link_to "削除する", admin_item_path(@item.id), method: :delete, "data-confirm" => "削除しますか？", class: "sp-font-12 btn btn-danger left-space-50" %></div>

</div>


<div>

  <div>

    <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>

    <div class="sp-font-12"><%= link_to "選び直す", edit_admin_item_path(@item.id) %></div>

    <!--カテゴリ選択-->
    <div class="space_15">
      <div class="top_10 space_10 sp-font-15">変更前：<%= @item.large_category.name %> ＞ <%= @item.medium_category.name %> ＞ <%= @item.small_category.name %></div>
      <div class="flex sp-font-12">

        <div>
          <label class="underline">大カテゴリ</label>
          <div>
          <% if @large_category.present? %>

            <%= @large_category.name %>
            <% elsif @medium_category.present? %>
              <%= @medium_category.large_category.name %>
            <% elsif @small_category.present? %>
              <%= @small_category.medium_category.large_category.name %>
            <% else %>
            <% @large_categories.each do |large_category| %>
              <%= link_to large_category.name, edit_admin_item_path(large_category_id: large_category.id) %>
            <br/>
            <% end %>

            <% end %>
          </div>
        </div>


        <div class="space"> ＞ </div>

        <div>
          <label class="underline">中カテゴリ</label>
          <% if @medium_categories.present? %>
          <div>
            <% @medium_categories.each do |medium_category| %>
              <%= link_to medium_category.name, edit_admin_item_path(medium_category_id: medium_category.id) %>
              <br/>
            <% end %>
          </div>
            <% elsif @medium_category.present? %>
              <br/><%= @medium_category.name %>
            <% elsif @small_category.present? %>
              <br/><%= @small_category.medium_category.name %>
            <% else %>
          <% end %>
        </div>

        <div class="space"> ＞ </div>

        <div>
          <label class="underline">小カテゴリ</label>
          <% if @small_categories.present? %>
          <div>
            <% @small_categories.each do |small_category| %>
              <%= link_to small_category.name, edit_admin_item_path(small_category_id: small_category.id) %>
              <br/>
            <% end %>
          </div>
            <% elsif @small_category.present? %>
              <br/><%= @small_category.name %>
            <% else %>
          <% end %>
        </div>

      </div>
    </div>
    <!---->

    <div>
      <table class="width-100p">
        <tr>
          <th class="sp-width-17p width-100">項目名</th>
          <td><%= f.text_field :name, :required => true %></td>
        </tr>
        <tr>
          <th>読み</th>
          <td><%= f.text_field :reading, :required => true %></td>
        </tr>
        <tr>
          <th>情報</th>
          <td><%= f.text_area :information, class: "width-50p height-100" %></td>
        </tr>
        <tr>
          <th>解説</th>
          <td><%= f.text_area :commentary, class: "width-70p height-100" %></td>
        </tr>
        <tr>
          <th>画像1</th>
          <td>
            変更前<%= image_tag @item.get_image(150, 150) %>
            <%= f.file_field :image, accept: "image/*" %>
          </td>
        </tr>
        <tr>
          <th>他画像</th>
          <td>
            ↓削除する画像をチェックしてください↓

          <% if @item.other_images.attached? %>
            <div class="column-2 width-50p">
              <% @item.other_images.each.with_index(2) do |other_image, i| %>
              <div class="space_15 avoid">
                <div>
                  <%= f.check_box :other_image_ids, { multiple: true }, other_image.id, false %>
                  <%= "画像" + i.to_s %>
                  <label for="item_other_image_ids_<%= other_image.id %>" >
                    <%= image_tag other_image, width: 150, height: 150 %>
                  </label>
                </div>

              </div>
              <% end %>
            </div>
          <% end %>

          <!--更新と削除同時にできないので、
          更新する場合は「追加する」ボタンを用意しておいて
          クリックするとフォームと注意書きが表示されるようにする。
          また、
          [:item][:other_images].present?
          かませて、これがある場合はフォームを表示させないようにする
          -->
          <%= f.file_field :other_images, accept: "image/*", multiple: true %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td><%= f.submit '更新する', class: "top_50 btn btn-primary sp-font-12" %></td>
        </tr>
      </table>
    </div>

    <% end %>

  </div>

</div>

app/views/admin/items/new.html.erb
<p>
  <% if @item.errors.any? %>
    <% @item.errors.full_messages.each do |messeage| %>
      <div>・<%= messeage %></div>
    <% end %>
  <% end %>
</p>

<div class="flex space_50 sp-font-12">


<div>
  <div class="title">項目追加</div>


  <!--カテゴリ選択-->
    <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

    <div><%= link_to "選び直す", new_admin_item_path(@item.id) %></div>

    <div class="flex space_50">

    <div>
      <label class="underline">大カテゴリ</label>
      <div>
      <% if @large_category.present? %>

        <%= @large_category.name %>
        <% elsif @medium_category.present? %>
          <%= @medium_category.large_category.name %>
        <% elsif @small_category.present? %>
          <%= @small_category.medium_category.large_category.name %>
        <% else %>
        <% @large_categories.each do |large_category| %>
          <%= link_to large_category.name, new_admin_item_path(large_category_id: large_category.id) %>
        <br/>
        <% end %>

        <% end %>

      </div>
    </div>

    <div class="space">＞</div>

    <div>
    <label class="underline">中カテゴリ</label>
    <% if @medium_categories.present? %>
    <div>
      <% @medium_categories.each do |medium_category| %>
        <%= link_to medium_category.name, new_admin_item_path(medium_category_id: medium_category.id) %>
        <br/>
      <% end %>
    </div>
      <% elsif @medium_category.present? %>
        <br/><%= @medium_category.name %>
      <% elsif @small_category.present? %>
        <br/><%= @small_category.medium_category.name %>
      <% else %>
    <% end %>

    </div>

    <div class="space">＞</div>

    <div>
    <label class="underline">小カテゴリ</label>
    <% if @small_categories.present? %>
    <div>
      <% @small_categories.each do |small_category| %>
        <%= link_to small_category.name, new_admin_item_path(small_category_id: small_category.id) %>
        <br/>
      <% end %>
    </div>
      <% elsif @small_category.present? %>
        <br/><%= @small_category.name %>
      <% else %>
    <% end %>
    </div>

    </div>
    <!---->


    <!--カテゴリ選択後に表示-->

    <% if @small_category.present? %>

    <div>
      <table class="width-100p">
        <tr>
          <th class="width-100">項目名</th>
          <td><%= f.text_field :name, :required => true %></td>
        </tr>
        <tr>
          <th>読み</th>
          <td><%= f.text_field :reading, :required => true %></td>
        </tr>
        <tr>
          <th>情報</th>
          <td><%= f.text_area :information, class: "height-100 width-100p" %></td>
        </tr>
        <tr>
          <th>解説</th>
          <td><%= f.text_area :commentary, class: "height-100 width-100p" %></td>
        </tr>
        <tr>
          <th>画像1</th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <th>他画像</th>
          <td><%= f.file_field :other_images, accept: "image/*", multiple: true %></td>
        </tr>
        <tr>
          <th></th>
          <td><%= f.submit '追加する', class: "top_50 btn btn-primary sp-font-11" %></td>
        </tr>
      </table>
    </div>

    <% else %>

    <div>カテゴリを選択してください。</div>

    <% end %>

    <!---->


    <% end %>


</div>


<div class="scroll height-680 left-space-30">
  <div>項目一覧</div>
  <% @large_categories.each do |large_category| %>
    〇<%= large_category.name %>

    <div class="left-space-10">
    <% large_category.medium_categories.each do |medium_category| %>
      ・<%= medium_category.name %>


      <div class="left-space-10">
      <% medium_category.small_categories.each do |small_category| %>
        ><%= small_category.name %>

        <div class="left-space-20">
        <% small_category.items.order(:reading).each do |item| %>
          -<%= link_to item.name, item_path(item.id) %>
          </br>
        <% end %>
        </div>

      <% end %>
      </div>

    <% end %>
    </div>

  <% end %>
</div>

</div>