config/routes.rb
Rails.application.routes.draw do

  scope module: 'public' do

    # homes
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    #customers
    resources :customers, only: [:edit]
    get 'customers/my_page' => 'customers#show'
    patch 'customers/infomation' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw'  => 'customers#withdraw'

    #large_categories
    get 'categories' => 'large_categories#index'

    #quizzes
    get 'quizzes' => 'quizzes#index'
    get 'quizzes/shuffle' => 'quizzes#shuffle'

    #mock_exams
    resources :mock_exams, only: [:index, :create, :show, :destroy]

    #answers
    resources :answers, only: [:create]

    #board_posts
    resources :board_posts, only: [:index, :new, :show, :create, :destroy]
    get 'board_post/my_posts' => 'board_posts#my_posts'

    #comments
    resources :comments, only: [:create, :destroy]
    get 'comment/my_comments' => 'comments#my_comments'

    #items
    resources :items, only: [:index, :show]


  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do

    #large_categories
    resources :large_categories, only: [:index]
    post 'large_create' => 'large_categories#large_create'
    delete 'large_destroy/:id' => 'large_categories#large_destroy', as: 'large_destroy'
    post 'medium_create' => 'large_categories#medium_create'
    delete 'medium_destroy/:id' => 'large_categories#medium_destroy', as: 'medium_destroy'
    post 'small_create' => 'large_categories#small_create'
    delete 'small_destroy/:id' => 'large_categories#small_destroy', as: 'small_destroy'

    #items
    resources :items, only: [:new, :create, :edit, :update, :destroy]

    #quizzes
    resources :quizzes, only: [:create, :edit, :update, :destroy]

    #customers
    resources :customers, only: [:index, :edit, :update]

    #bord_posts
    resources :board_posts, only: [:destroy]

    #comments
    resources :comments, only: [:destroy]

  end

end

app/models/large_category.rb
class LargeCategory < ApplicationRecord

  has_many :items, dependent: :destroy
  has_many :medium_categories, dependent: :destroy

end

app/controllers/admin/large_categories_controller.rb
class Admin::LargeCategoriesController < ApplicationController

  Item.order(:name)

  def index
    if admin_signed_in?
      # すべて表示
      @large_categories = LargeCategory.all
      @large_category = LargeCategory.new
      @medium_category = MediumCategory.new
      @small_category = SmallCategory.new
      @@large_select = 0
      @@medium_select = 0

      @items = Item.all
      @quizzes = Quiz.all

      if params[:large_category_id].present?
        @@large_select = LargeCategory.find(params[:large_category_id])
        @large_select = @@large_select
        @medium_selects = @@large_select.medium_categories
      end

      if params[:medium_category_id].present?
        @@medium_select = MediumCategory.find(params[:medium_category_id])
        @medium_select = @@medium_select
      end
    else
      redirect_to root_path
    end
  end

  # 大カテゴリ

  def large_create
    @large_category = LargeCategory.new(large_category_params)
    if @large_category.save
      redirect_to admin_large_categories_path
    else
      @large_categories = LargeCategory.all
      @medium_categories = MediumCategory.all
      @small_categories = SmallCategory.all
      render :index
    end
  end

  def large_destroy
    if admin_signed_in?
      @large_categories = LargeCategory.find(params[:id])
      @large_categories.destroy
      redirect_to admin_large_categories_path
    else
      redirect_to root_path
    end
  end

  # 中カテゴリ

  def medium_create
    @medium_category = MediumCategory.new(medium_category_params)
    @large_category = LargeCategory.new
    @small_category = SmallCategory.new
    if @@large_select == 0
    else
      @medium_category.large_category_id = @@large_select.id
    end

    if @medium_category.save
      redirect_to admin_large_categories_path
    else
      @large_categories = LargeCategory.all
      @@large_select = 0
      render :index
    end
  end

  def medium_destroy
    if admin_signed_in?
      @medium_categories = MediumCategory.find(params[:id])
      @medium_categories.destroy
      redirect_to admin_large_categories_path
    else
      redirect_to root_path
    end
  end

  # 小カテゴリ

  def small_create
    @small_category = SmallCategory.new(small_category_params)
    @large_category = LargeCategory.new
    @medium_category = MediumCategory.new
    if @@medium_select == 0
    else
      @small_category.medium_category_id = @@medium_select.id
    end

    if @small_category.save
      redirect_to admin_large_categories_path
    else
      @large_categories = LargeCategory.all
      @@medium_select = 0
      render :index
    end
  end

  def small_destroy
    if admin_signed_in?
      @small_categories = SmallCategory.find(params[:id])
      @small_categories.destroy
      redirect_to admin_large_categories_path
    else
      redirect_to root_path
    end
  end

  private

  def large_category_params
    params.require(:large_category).permit(:name)
  end

  def medium_category_params
    params.require(:medium_category).permit(:name, :large_category_id)
  end

  def small_category_params
    params.require(:small_category).permit(:name, :medium_category_id)
  end

end

app/helpers/admin/large_categories_helper.rb
module Admin::LargeCategoriesHelper
end

app/views/admin/large_categories/index.html.erb
<div class="title">カテゴリ管理</div>

<div class="flex width-100p sp-font-12">


<div class="width-50p">


  <div><%= link_to "選び直す", admin_large_categories_path %></div>

  <div>

  <div>
    <!--大カテ追加-->
      <%= form_with model: @large_category, url: admin_large_create_path, method: :post do |f| %>
      <div class="top_30 flex">
        <div><%= f.text_field :name, placeholder: "大カテゴリ追加", :required => true, class: "sp-width-120px" %></div>
        <div><%= f.submit '追加する' %></div>
      </div>
      <% end %>
    <!---->
  </div>
</div>
  <div>

<br/>

    <!--大カテ選択-->
    <div class="font-20 space_10 underline">大カテ選択</div>
    <% if @large_select.present? %>
      > <%= @large_select.name %> <
    <% elsif @medium_select.present? %>
      > <%= @medium_select.large_category.name %> <
    <% else %>
    <div class="space_30">
      <% @large_categories.each do |large_category| %>
        <div><%= link_to large_category.name, admin_large_categories_path(large_category_id: large_category.id) %></div>
      <% end %>
    </div>
    <% end %>
    <!---->


    <!--中カテ追加-->

    <% if @large_select.present? %>

      <div>
        <%= form_with model: @medium_category, url: admin_medium_create_path, method: :post do |f| %>
        <div class="top_20 flex">
          <div><%= f.text_field :name, placeholder: "中カテゴリ追加", :required => true, class: "sp-width-120px" %></div>
          <div><%= f.submit '追加する' %></div>
        </div>
        <% end %>
      </div>

    <% else %>
      <div class="top_20">大カテゴリを選択してください。</div>
    <% end %>
    <!---->

    </div>

<br/>

  <div>
    <!--中カテ選択-->
    <% if @medium_selects.present? %>
    <div class="font-20 space_10 underline">中カテ選択</div>
      <div>
        <% @medium_selects.each do |medium_category| %>
          <div><%= link_to medium_category.name, admin_large_categories_path(medium_category_id: medium_category.id) %></div>
        <% end %>
      </div>
    <% elsif @medium_select.present? %>
      <div>> <%= @medium_select.name %> <</div>
    <% else %>
    <% end %>
    <!---->

    <!--小カテ追加-->

    <% if @medium_select.present?  %>

      <%= form_with model: @small_category, url: admin_small_create_path, method: :post do |f| %>
      <div class="top_20 flex">
        <div><%= f.text_field :name, placeholder: "小カテゴリ追加", :required => true, class: "sp-width-120px" %></div>
        <div><%= f.submit '追加する' %></div>
      </div>
      <% end %>

    <% else %>
      <div class="top_20">中カテゴリを選択してください。</div>
    <% end %>
    <!---->
  </div>
</div>

<!--カテゴリ一覧-->
<div class="scroll right-send height-680">

  <div>

    <div>

    <div class="avoid">
    <% @large_categories.each do |large_category| %>
    <div class="underline font-20">
      <%= link_to large_category.name, admin_large_destroy_path(large_category), method: :delete, "data-confirm" => "削除しますか？" %>
      <label class="font-12 top-bottom-text-center">(<%= large_category.medium_categories.count %>)</label>
    </div>

    <div>
    <% large_category.medium_categories.each do |medium_category| %>
    <div class="left-space-10">
      ●<%= link_to medium_category.name, admin_medium_destroy_path(medium_category), method: :delete, "data-confirm" => "削除しますか？" %>
      <label class="font-12 top-bottom-text-center">(<%= medium_category.small_categories.count %>)</label>
    </div>
    <div>
    <% medium_category.small_categories.each do |small_category| %>
    <div class="left-space-20">
      ><%= link_to small_category.name, admin_small_destroy_path(small_category), method: :delete, "data-confirm" => "削除しますか？" %>
      <label class="font-12 top-bottom-text-center">(<%= small_category.items.count %>)</label>
    </div>

    <% end %>
    </div>
    <% end %>
    </div>
    <% end %>
    </div>

    </div>
  </div>

</div>
<!---->

</div>