config/routes.rb
Rails.application.routes.draw do

  scope module: 'public' do

    # homes
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    #customers
    resources :customers, only: [:edit]
    get 'customers/my_page' => 'customers#show'
    patch 'customers/infomation' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw'  => 'customers#withdraw'

    #large_categories
    get 'categories' => 'large_categories#index'

    #quizzes
    get 'quizzes' => 'quizzes#index'
    get 'quizzes/shuffle' => 'quizzes#shuffle'

    #mock_exams
    resources :mock_exams, only: [:index, :create, :show, :destroy]

    #answers
    resources :answers, only: [:create]

    #board_posts
    resources :board_posts, only: [:index, :new, :show, :create, :destroy]
    get 'board_post/my_posts' => 'board_posts#my_posts'

    #comments
    resources :comments, only: [:create, :destroy]
    get 'comment/my_comments' => 'comments#my_comments'

    #items
    resources :items, only: [:index, :show]


  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do

    #large_categories
    resources :large_categories, only: [:index]
    post 'large_create' => 'large_categories#large_create'
    delete 'large_destroy/:id' => 'large_categories#large_destroy', as: 'large_destroy'
    post 'medium_create' => 'large_categories#medium_create'
    delete 'medium_destroy/:id' => 'large_categories#medium_destroy', as: 'medium_destroy'
    post 'small_create' => 'large_categories#small_create'
    delete 'small_destroy/:id' => 'large_categories#small_destroy', as: 'small_destroy'

    #items
    resources :items, only: [:new, :create, :edit, :update, :destroy]

    #quizzes
    resources :quizzes, only: [:create, :edit, :update, :destroy]

    #customers
    resources :customers, only: [:index, :edit, :update]

    #bord_posts
    resources :board_posts, only: [:destroy]

    #comments
    resources :comments, only: [:destroy]

  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:name]

  validates_uniqueness_of :name
  validates_presence_of :name

  has_many :mock_exams, dependent: :destroy

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["name = :value", { :value => name }]).first
    else
      where(conditions).first
    end
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

   def will_save_change_to_email?
     false
   end

  def active_for_authentication?
    super && (is_active == true)
  end


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    if admin_signed_in?
      @customers = Customer.all
    else
      redirect_to root_path
    end
  end

  def edit
    if admin_signed_in?
      @customer = Customer.find(params[:id])
    end
  end

  def update
    @customer = Customer.find(params[:id])
    if admin_signed_in?
      if @customer.update(customer_params)
        redirect_to admin_customers_path
      else
        render :edit
      end
    else
      redirect_to root_path
    end
  end

  def customer_params
    params.require(:customer).permit(:name, :is_active)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<p>
  <% if @customer.errors.any? %>
    <% @customer.errors.full_messages.each do |messeage| %>
      <div>・<%= messeage %></div>
    <% end %>
  <% end %>
</p>


<div class="title"><%= @customer.name %>さんの会員情報編集</div>


<%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>


<table>
  <tr>
    <th>会員ID</th>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <th>ユーザ名</th>
    <td><%= f.text_field :name, :required => true %></td>
  </tr>
  <tr>
    <th>会員ステータス</th>
    <td>
      <div>
        <%= f.radio_button :is_active, true %>
        <label>有効</label>
      </div>
      <div>
        <%= f.radio_button :is_active, false %>
        <label>退会</label>
      </div>
    </td>
  </tr>
  <tr>
    <th></th>
    <td><%= f.submit '変更を保存', class: 'btn btn-success' %></td>
  </tr>
</table>


<% end %>

app/views/admin/customers/index.html.erb
<div class="title">会員一覧</div>

<div>

  <table>

    <thead class="text-center">
      <tr>
        <th class="outline">ID</th>
        <th class="outline">ユーザ名</th>
        <th class="outline">ステータス</th>
      </tr>
    </thead>
    <% @customers.each do |customer| %>
    <tbody class="text-center">
      <tr>
        <td class="outline"><%= customer.id %></td>
        <td class="outline"><%= link_to customer.name, edit_admin_customer_path(customer.id) %></td>
        <td class="outline">
          <% if customer.is_active %>
            <div class="true">有効</div>
          <% else %>
            <div class="false">退会</div>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>

  </table>


</div>