config/routes.rb
Rails.application.routes.draw do

  scope module: 'public' do

    # homes
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'

    #customers
    resources :customers, only: [:edit]
    get 'customers/my_page' => 'customers#show'
    patch 'customers/infomation' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw'  => 'customers#withdraw'

    #large_categories
    get 'categories' => 'large_categories#index'

    #quizzes
    get 'quizzes' => 'quizzes#index'
    get 'quizzes/shuffle' => 'quizzes#shuffle'

    #mock_exams
    resources :mock_exams, only: [:index, :create, :show, :destroy]

    #answers
    resources :answers, only: [:create]

    #board_posts
    resources :board_posts, only: [:index, :new, :show, :create, :destroy]
    get 'board_post/my_posts' => 'board_posts#my_posts'

    #comments
    resources :comments, only: [:create, :destroy]
    get 'comment/my_comments' => 'comments#my_comments'

    #items
    resources :items, only: [:index, :show]


  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do

    #large_categories
    resources :large_categories, only: [:index]
    post 'large_create' => 'large_categories#large_create'
    delete 'large_destroy/:id' => 'large_categories#large_destroy', as: 'large_destroy'
    post 'medium_create' => 'large_categories#medium_create'
    delete 'medium_destroy/:id' => 'large_categories#medium_destroy', as: 'medium_destroy'
    post 'small_create' => 'large_categories#small_create'
    delete 'small_destroy/:id' => 'large_categories#small_destroy', as: 'small_destroy'

    #items
    resources :items, only: [:new, :create, :edit, :update, :destroy]

    #quizzes
    resources :quizzes, only: [:create, :edit, :update, :destroy]

    #customers
    resources :customers, only: [:index, :edit, :update]

    #bord_posts
    resources :board_posts, only: [:destroy]

    #comments
    resources :comments, only: [:destroy]

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NOKAN</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script src="https://kit.fontawesome.com/6691dd93a4.js" crossorigin="anonymous"></script>


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>


    <header>
      <div class="width-100p">
        <!--ロゴ-->
        <div><%= link_to "NOKAN", root_path, class: 'logo font-25' %></div>

        <div>
          <!--ようこそ〇〇さん-->
          <% if customer_signed_in? %>
          <div class="welcome">ようこそ、<%= current_customer.name %>さん！</div>
          <% elsif admin_signed_in? %>
          <div class="welcome">管理者ログイン中</div>
          <% end %>
        </div>

        <div class="list">

          <ul>
            <!--管理者ログイン-->
            <% if admin_signed_in? %>
            <li><%= link_to "項目追加", new_admin_item_path, class: 'header-btn' %></li>
            <li><%= link_to "会員一覧", admin_customers_path, class: 'header-btn' %></li>
            <li><%= link_to "カテゴリ", admin_large_categories_path, class: 'header-btn' %></li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'header-btn' %></li>

            <!--会員ログイン-->
            <% elsif customer_signed_in? %>
            <li><%= link_to "トップ", root_path, class: 'header-btn' %></li>
            <li><%= link_to "マイページ", customers_my_page_path, class: 'header-btn' %></li>
            <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'header-btn' %></li>

            <!--共通ログアウト-->
            <% else %>
            <li><%= link_to "トップ", root_path, class: 'header-btn' %></li>
            <li><%= link_to "About", about_path, class: 'header-btn' %></li>
            <li><%= link_to "ログイン", new_customer_session_path, class: 'header-btn' %></li>

            <% end %>
          </ul>

        </div>

      </div>
    </header>


    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer></footer>

  </body>
</html>